#!/usr/bin/env python3
"""
configure.py — 插件自动发现与配置生成

扫描 plugins/ 目录，检测每个插件实现的 hook，
生成 include/pool_plugin_config.h。

用法:
    python3 configure.py                          # 默认扫描 plugins/
    python3 configure.py --plugin-dir my_plugins  # 指定目录
    python3 configure.py --dry-run                 # 仅打印，不写文件
    python3 configure.py --output custom_path.h    # 指定输出路径

约定:
    plugins/
      <插件名>/
        plugin.h   ← 必需：hook 函数声明
        plugin.c   ← 可选：实现

    函数命名: {插件名}_{hook名}
    例如 swap_post_alloc(void *ctx, pool_cfg_t *cfg, ...)

    每个插件可声明一个全局上下文变量 {插件名}_ctx，
    类型自定，在 plugin.h 中 extern，在 plugin.c 中定义。
"""

import os
import re
import sys
import argparse

# ================================================================
# Hook 签名表 — 每个 hook 的 C 参数列表和调用实参
# ================================================================

HOOK_SIGNATURES = {
    "post_init": {
        "params": "pool_cfg_t *cfg",
        "args":   "cfg",
    },
    "post_alloc": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t start, uint32_t count, uint32_t handle",
        "args":   "cfg, owner, start, count, handle",
    },
    "pre_free": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle",
        "args":   "cfg, owner, handle",
    },
    "post_free": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle",
        "args":   "cfg, owner, handle",
    },
    "pre_lock": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle",
        "args":   "cfg, owner, handle",
    },
    "post_lock": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle, void *addr",
        "args":   "cfg, owner, handle, addr",
    },
    "pre_unlock": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle",
        "args":   "cfg, owner, handle",
    },
    "post_unlock": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle",
        "args":   "cfg, owner, handle",
    },
    "pre_resize": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle, uint32_t old_pages, uint32_t new_pages",
        "args":   "cfg, owner, handle, old_pages, new_pages",
    },
    "post_resize": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t handle, uint32_t old_pages, uint32_t new_pages",
        "args":   "cfg, owner, handle, old_pages, new_pages",
    },
    "defrag_move": {
        "params": "pool_cfg_t *cfg, uint32_t src_page, uint32_t dst_page, uint32_t count, uint32_t handle_idx",
        "args":   "cfg, src_page, dst_page, count, handle_idx",
    },
    "pre_defrag": {
        "params": "pool_cfg_t *cfg",
        "args":   "cfg",
    },
    "post_defrag": {
        "params": "pool_cfg_t *cfg",
        "args":   "cfg",
    },
    "pre_free_all": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t forced",
        "args":   "cfg, owner, forced",
    },
    "post_free_all": {
        "params": "pool_cfg_t *cfg, pool_owner_t *owner, uint32_t forced",
        "args":   "cfg, owner, forced",
    },
}

HOOK_MACRO_PREFIX = "POOL_HOOK_"


# ================================================================
# 扫描逻辑
# ================================================================

def scan_plugins(plugin_dir):
    """
    扫描 plugin_dir 中的每个子目录，
    返回 {插件名: [hook名列表]}
    """
    plugins = {}

    if not os.path.isdir(plugin_dir):
        return plugins

    for entry in sorted(os.listdir(plugin_dir)):
        plugin_path = os.path.join(plugin_dir, entry)
        if not os.path.isdir(plugin_path):
            continue

        header = os.path.join(plugin_path, "plugin.h")
        if not os.path.isfile(header):
            continue

        with open(header, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()

        hooks = []
        for hook_name in HOOK_SIGNATURES:
            # 匹配模式: {entry}_{hook_name}\s*\(
            # entry 是插件名（即目录名），可能与 hook_name 中有下划线
            # 简单处理：函数名必须以插件名开头，以 _{hook_name}( 结尾
            pattern = rf'\b{re.escape(entry)}_{re.escape(hook_name)}\s*\('
            if re.search(pattern, content):
                hooks.append(hook_name)

        if hooks:
            plugins[entry] = hooks

    return plugins


# ================================================================
# 生成逻辑
# ================================================================

def generate_config(plugins, plugin_dir):
    """生成 pool_plugin_config.h 内容"""
    lines = []
    lines.append("/* Auto-generated by configure.py — DO NOT EDIT */")
    lines.append("/*")
    lines.append(" * Plugins found:")
    if plugins:
        for name in sorted(plugins):
            lines.append(f" *   {name}  →  {', '.join(plugins[name])}")
    else:
        lines.append(" *   (none)")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef POOL_PLUGIN_CONFIG_H")
    lines.append("#define POOL_PLUGIN_CONFIG_H")
    lines.append("")

    # 包含插件头文件
    for name in sorted(plugins):
        lines.append(f'#include "../{plugin_dir}/{name}/plugin.h"')
    if plugins:
        lines.append("")

    # 为每个 hook 生成宏覆盖
    for hook_name in HOOK_SIGNATURES:
        macro_name = f"{HOOK_MACRO_PREFIX}{hook_name.upper()}"
        sig = HOOK_SIGNATURES[hook_name]

        # 找到实现了这个 hook 的插件
        active = [name for name in sorted(plugins) if hook_name in plugins[name]]

        if not active:
            # 无需覆盖，pool_hooks.h 已提供默认空定义
            continue

        # 生成宏：取消旧定义 → 新定义 = 调用链
        lines.append(f"/* {hook_name} — implemented by: {', '.join(active)} */")
        lines.append(f"#undef {macro_name}")

        call_chain_parts = []
        for name in active:
            call_chain_parts.append(
                f"    {name}_{hook_name}(&{name}_ctx, {sig['args']})"
            )

        call_chain = "; \\\n".join(call_chain_parts) + ";"

        lines.append(
            f"#define {macro_name}({sig['args']}) \\\n"
            f"{call_chain}"
        )
        lines.append("")

    lines.append("#endif /* POOL_PLUGIN_CONFIG_H */")
    return "\n".join(lines) + "\n"


# ================================================================
# 主流程
# ================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Pool plugin auto-discovery and config generator"
    )
    parser.add_argument(
        "--plugin-dir", default="plugins",
        help="Plugin directory (default: plugins/)"
    )
    parser.add_argument(
        "--output", default="include/pool_plugin_config.h",
        help="Output header path (default: include/pool_plugin_config.h)"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print generated config to stdout, do not write file"
    )
    args = parser.parse_args()

    plugins = scan_plugins(args.plugin_dir)
    config = generate_config(plugins, args.plugin_dir)

    if args.dry_run:
        print(config)
    else:
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(config)
        print(f"Generated {args.output}")
        if plugins:
            print(f"Plugins: {', '.join(sorted(plugins))}")
        else:
            print("No plugins found.")


if __name__ == "__main__":
    main()